on: push

jobs:
 build_image:
    runs-on: ubuntu-latest
    name: Builds image and pushes to Dockerhub
    steps:
    - uses: actions/checkout@v1
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: daghaian/netflix-top-list-scraper
        tags: latest

 run_scraper:
    runs-on: ubuntu-latest
    needs: build_image
    env:
        TRAKT_API_KEY: ${{ secrets.TRAKT_API_KEY }}
        TRAKT_ACCESS_TOKEN: ${{ secrets.TRAKT_ACCESS_TOKEN }}
        TRAKT_MOVIE_LIST: ${{ secrets.TRAKT_MOVIE_LIST }}
        TRAKT_TV_LIST: ${{ secrets.TRAKT_TV_LIST }}
        NETFLIX_USERNAME: ${{ secrets.NETFLIX_USERNAME }}
        NETFLIX_PASSWORD: ${{ secrets.NETFLIX_PASSWORD }}
    steps:
    - uses: actions/checkout@v1
    - name: Run scraper 
      uses: ./
     
